DROP TABLE IF EXISTS USER;
  
CREATE TABLE USER (
  user_Id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  address VARCHAR(250) NOT NULL,
  access_Token VARCHAR(250) DEFAULT NULL
);

CREATE TABLE ARTICLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  body VARCHAR(250) NOT NULL,
  author VARCHAR(250) DEFAULT NULL,
  created_By VARCHAR(250) NOT NULL
 );